nishiki-tech/nishiki-documents

project-document/docusaurus.config.js

Fixed a tiny problem in docusaurus config.

fix: fix wrong repo name

---

.github/ISSUE_TEMPLATE/enhancement_comunity.md
.github/ISSUE_TEMPLATE/enhancement_team.md
.github/ISSUE_TEMPLATE/problem_comunity.md
.github/ISSUE_TEMPLATE/problem_team.md
.github/ISSUE_TEMPLATE/question_comunity.md
.github/ISSUE_TEMPLATE/question_team.md
.github/PULL_REQUEST_TEMPLATE/community.md
.github/PULL_REQUEST_TEMPLATE/team.md
docs/CONTRIBUTING.md

Added general md documents.
* Added issue templates for both team and community contributors to the `.github/ISSUE_TEMPLATE/` directory
* Added pull request templates to the `.github/PULL_REQUEST_TEMPLATE/` directory
* Added `CONTRIBUTING.md` to the `docs/` directory

Add issue and pull request templates, CONTRIBUTION.md

---

project-document/docs/domain-model/user-context/user.md

added a lower limit to the user domain document.

fix: added a lower limit

---

project-document/docs/domain-model/domain-model.md

Standardized Expiry ubiquitous.

update: Expire -> Expiry

---

project-document/docs/domain-model/group-context/food.md
project-document/docs/er-diagram/er-diagram.md

- add a Unit section in the Food model description.
- add unit, quantity, and expiry in the Food entity in the ER diagram.

modify: document about food especially unit

---

project-document/docs/intro.md

updated the welcome page in the project document.

feat: updated the welcome page

---

project-document/docs/domain-model/domain-model.md

The UserId and ContaienrId turned into the composition of the Group

doc: update domain model diagram

---

project-document/docs/database/er-diagram.md

Added the User table and UserGroup table connection

fix: added User and UserGroup connection

---

web-api/nishiki-web-api.yaml

Added the group response model.
#59

updated the group model

---

web-api/nishiki-web-api.yaml

Added an auth me endpoint

---

web-api/nishiki-web-api.yaml

DELETE /users/{userId}/containers endpoint
Add GET /containers endpoint

update get containers endpoint

---

web-api/nishiki-web-api.yaml

Changed the return value as an object from a list.
The actual values are the same, but those are wrapped by an object. 
```json
[
{
"containerDetail": "detail" // container ID so on
}
]
```
```json
{
"containers": [
{
"containerDetail": "detail" // container ID so on
}
]
}
```

nested a container list into the container object.

---

web-api/nishiki-web-api.yaml

fix: /groups/:groupId/users API response type

---

web-api/nishiki-web-api.yaml

Added a delete a container API

Added a delete container API

---

web-api/nishiki-web-api.yaml

Added an update container name API

added an update container name API.

---

web-api/nishiki-web-api.yaml

Updated put and delete operations' status code from 202 to 204.

fixed some status codes

---

project-document/docs/database/database.md

Fix the wording of the join link expiry Datetime

Fix woding of join link expiry Datetime

---

project-document/docs/database/database.md

To optimize the performance and the cost, it's needed to remove the SK, which is the UserId attribute.

Delete an SK of the user and group relations

---

web-api/nishiki-web-api.yaml

- Added `category` attributes to food entity
- `category` is string value
- number of `category` for each food is ~~0 or 1~~ 1

Added category attributes to food entity

---

web-api/nishiki-web-api.yaml

Fix for #89
I would like to be checked after discussion at issue.

feat: added groupName to container object

---

web-api/nishiki-web-api.yaml

doc: added createdAt attribute to Food properties

---

project-document/docs/database/database.md

Removed the InvitationLinkExpiryDatetime GSI

removed the InvitationLinkExpiryDatetime GSI

---

web-api/nishiki-web-api.yaml

- Fixed GET /container response data from single container object to multiple containers and food objects.
New mock response data example
```
{
"containers": [
{
"id": "11111111-ee7b-4558-b8d5-371514e77bed",
"name": "Shared-house's Fridge",
"groupId": "a3kdifut-a520-c2cb-1be7-d90710691861",
"groupName": "Shared-house",
"foods": [
{
"id": "11111111-58b7-4c3d-9548-fc0a4d3b3ef4",
"name": "arugula",
"quantity": 500,
"category": "vegetables",
"unit": "g",
"expiry": "2023-12-10T00:00:00.000Z",
"createdAt": "2023-12-01T00:00:00.000Z"
},
{
"id": "22222222-58b7-4c3d-9548-fc0a4d3b3ef4",
"name": "tomato",
"quantity": 5,
"category": "vegetables",
"unit": null,
"expiry": "2023-12-25T00:00:00.000Z",
"createdAt": "2023-12-04T00:00:00.000Z"
}
]
},
{
"id": "22222222-ee7b-4558-b8d5-371514e77bed",
"name": …
```

Fixed GET /container response data from single container object to multiple container and food object.

---

project-document/docs/database/database.md

Added a new access pattern, `GetUser`.

Added a `GetUser` access pattern

---

web-api/nishiki-web-api.yaml

Made all props required in these endpoints.
https://genesis-tech-tribe.github.io/nishiki-documents/web-api/#tag/container/paths/~1containers~1%7BcontainerId%7D~1foods/post
https://genesis-tech-tribe.github.io/nishiki-documents/web-api/#tag/container/paths/~1containers~1%7BcontainerId%7D~1foods~1%7BfoodId%7D/put

docs: make food's props required

---

web-api/nishiki-web-api.yaml

feat: fix group schema at container object

---

project-document/docs/database/database.md

Fixed the food name's data type from the nullable to the non-nullable string.
Related to [this issue](https://github.com/genesis-tech-tribe/nishiki-backend/pull/180#discussion_r1435554792).

foods data type

---

web-api/nishiki-web-api.yaml

add API endpoint to delete group
add API endpoint to update group name
( Sorry, I accidentally include this issue.
https://github.com/genesis-tech-tribe/nishiki-documents/issues/117
Is the following description's behavior fine? 
`This operation also deletes all containers and foods in the group.`

doc: add delete group endpoint

---

web-api/nishiki-web-api.yaml

- Add example to groups for API mock server.

Add mock API example to GET /groups

---

project-document/docs/specifications/others.md
project-document/sidebars.js
web-api/nishiki-web-api.yaml

Added a timezone specification

Added a timezone specification

---

project-document/docs/specifications/terms.md

Added the default username specification

Added the default username specification

---

project-document/docs/database/database.md

make sure this change meets our requirements.

doc: update the type of category

---

web-api/nishiki-web-api.yaml

Changed the status code of the joining the group API

Changed the status code of the joining the group API

---

web-api/nishiki-web-api.yaml

- Corrected description of endpoints for removing the user from their specific group

doc: modified description of endpoints for removing the user from their specific group

---

.github/workflows/invoke-schema-update-event.yml
README.md
project-document/docs/system-architecture/functions/user-initialize-function.md
project-document/docs/system-architecture/overview.md
project-document/docusaurus.config.js

Replaced the domain name in the URL

Fix: Hard coded URL

---

web-api/nishiki-web-api.yaml

Changed the data format of the quantity of food from int32 to float

Fix: Changed the data format of the quantity of the food

---

web-api/nishiki-web-api.yaml

Changed the container creation's input type from nullable to not nullable.

Fix: changed the container creation's input

---

web-api/nishiki-web-api.yaml

change the container update input type from nullable to not nullable

Fix: change container update input

---

web-api/nishiki-web-api.yaml

Added the DELETE /users/:id endpoint

Feat: added the DELETE /users/:id endpoint
